-- MySQL Script generated by MySQL Workbench
-- mar 08 ene 2019 19:36:17 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `delivery`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `ape1` VARCHAR(255) NULL,
  `ape2` VARCHAR(255) NULL,
  `telefono` INT NULL,
  `login` VARCHAR(255) NULL,
  `pass` VARCHAR(512) NULL,
  `email` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `poblacion` VARCHAR(255) NULL,
  `token` VARCHAR(255) NULL,
  `validado` TINYINT(1) NULL,
  `id_tipousuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipoUsuario_idx` (`id_tipousuario` ASC),
  CONSTRAINT `fk_usuario_tipousuario`
    FOREIGN KEY (`id_tipousuario`)
    REFERENCES `delivery`.`tipousuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `delivery`.`tipoproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tipoproducto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `delivery`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL,
  `desc` VARCHAR(255) NULL,
  `existencias` INT NULL,
  `precio` FLOAT NULL,
  `foto` VARCHAR(512) NULL,
  `id_tipoproducto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_tipoproducto1_idx` (`id_tipoproducto` ASC),
  CONSTRAINT `fk_producto_tipoProducto1`
    FOREIGN KEY (`id_tipoproducto`)
    REFERENCES `delivery`.`tipoproducto` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `delivery`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`restaurante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `poblacion` VARCHAR(255) NULL,

  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `iva` FLOAT NULL,
  `id_usuario` INT NULL,
  `id_restaurante` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_factura_restaurante1_idx` (`id_restaurante` ASC),
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `delivery`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_restaurante1`
    FOREIGN KEY (`id_restaurante`)
    REFERENCES `delivery`.`restaurante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `delivery`.`linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`linea` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `id_producto` INT NULL,
  `id_factura` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_linea_producto1_idx` (`id_producto` ASC),
  INDEX `fk_linea_factura1_idx` (`id_factura` ASC),
  CONSTRAINT `fk_linea_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `delivery`.`producto` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_linea_factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `delivery`.`factura` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `delivery`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `poblacion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`zona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_restaurante` INT NULL,
  `id_municipio` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zona_restaurante1_idx` (`id_restaurante` ASC),
  INDEX `fk_zona_municipio1_idx` (`id_municipio` ASC),
  CONSTRAINT `fk_zona_restaurante1`
    FOREIGN KEY (`id_restaurante`)
    REFERENCES `delivery`.`restaurante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zona_municipio1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `delivery`.`municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
